export { getAssaultRifleAttachments } from "./get/getAssaultRifleAttachments";
export { getBattleRifleAttachments } from "./get/getBattleRifleAttachments";
export { getLauncherAttachments } from "./get/getLauncherAttachments";
export { getLmgAttachments } from "./get/getLmgAttachments";
export { getMarksmanRifleAttachments } from "./get/getMarksmanRifleAttachments";
export { getPistolAttachments } from "./get/getPistolAttachments";
export { getShotgunAttachments } from "./get/getShotgunAttachments";
export { getSmgAttachments } from "./get/getSmgAttachments";
export { getSniperAttachments } from "./get/getSniperAttachments";
